name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test-php:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: laravel_test
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer

      - name: Install PHP dependencies
        run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

      - name: Setup environment file
        run: cp .env.example .env

      - name: Set database config
        run: |
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=laravel_test" >> .env
          echo "DB_USERNAME=user" >> .env
          echo "DB_PASSWORD=password" >> .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: ./vendor/bin/phpunit

  deploy:
    needs: test-php
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Connect to AWS EC2 & Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS }}
          SERVER_IP: ${{ secrets.AWS_SERVER_IP }}
          USER: ${{ secrets.AWS_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem

          ssh -o StrictHostKeyChecking=no -i deploy_key.pem $USER@$SERVER_IP << 'EOF'
            echo "✅ Connected to AWS EC2"

            # Ensure project directory exists
            mkdir -p /home/ubuntu/my-app
            cd /home/ubuntu/my-app || exit 1

            # Clone or pull the latest code
            if [ ! -d ".git" ]; then
              git clone git@github.com:AymaneQualiso/laravel-circle-ci.git .
            else
              git reset --hard
              git pull origin main || true
            fi

          EOF
